# Generated by Django 6.0.2 on 2026-02-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('RAM', 'Memory'), ('MB', 'Motherboard'), ('STR', 'Storage'), ('PSU', 'Power Supply')], max_length=3)),
                ('weight_g', models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hardware.brand')),
            ],
        ),
    ]
