# Generated by Django 6.0.2 on 2026-02-10 17:22

import showcase.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='description',
            field=models.TextField(validators=[showcase.validators.validate_no_console]),
        ),
    ]
